services:
  postgres:
    image: postgres:16
    hostname: postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - ./env/dev.env
      - ./env/docker.env
      - ./env/postgres.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    hostname: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    hostname: server
    depends_on:
      - postgres
    restart: always
    env_file:
      - ./env/dev.env
      - ./env/docker.env
      - ./env/app.env
    entrypoint: /docker/scripts/django.sh
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8080:8080"
    volumes:
      - ./gradle:/app/gradle/
      - ./src:/app/src/
      - ./gradlew:/app/gradlew:ro
    healthcheck:
      test: [ "CMD", "curl", "localhost:8000/health" ]
      interval: 120s
      timeout: 10s
      retries: 3


volumes:
  cache:
  postgres-db: